'use client';

import React from 'react';
import { Heart, Download } from 'lucide-react';

type ModelImageProps = {
  imageUrl?: string;
  modelName: string;
  isGenerating: boolean;
};

const ModelImage: React.FC<ModelImageProps> = ({ imageUrl, modelName, isGenerating }) => {
  return (
    <div className="flex flex-col items-center">
      <div className="relative group aspect-square w-full bg-gray-100 rounded-lg overflow-hidden mb-2">
        {imageUrl ? (
          <img
            src={imageUrl}
            alt={`Generated by ${modelName}`}
            className="w-full h-full object-cover"
          />
        ) : (
          <div className="w-full h-full flex items-center justify-center text-gray-400">
            {isGenerating ? 'Generating...' : 'Image will appear here'}
          </div>
        )}
        {imageUrl && (
          <div className="absolute inset-0 bg-black bg-opacity-50 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center">
            <button className="text-white mr-2">
              <Heart size={24} />
            </button>
            <button className="text-white">
              <Download size={24} />
            </button>
          </div>
        )}
      </div>
      <div className="text-center">
        <p className="font-semibold">{modelName}</p>
      </div>
    </div>
  );
};

export default ModelImage;
